### ISSUE TITLE
Error require() of ES Module not supported.

### ISSUE THREAD

**Issue by patrickcate** [tgamauf/cypress-parallel#9]
Greetings,

I'm trying to setup this GHA but have run into an some issues.

with a `cypress.config.mjs` file I get the following error.

```shell
Error: Failed to parse cypress tests: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/REDACTED/REDACTED/tests/cypress.config.mjs not supported.
Instead change the require of /home/runner/work/REDACTED/REDACTED/tests/cypress.config.mjs to a dynamic import() which is available in all CommonJS modules.
```

I tried renaming the config file to `cypress.config.js` and also needed to add the `"type": "module"` to the `package.json` file in order for Cypress to run at all. With this change I got the following error.

```shell
Error: Failed to parse cypress tests: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/REDACTED/REDACTED/tests/cypress.config.js from /home/runner/work/_actions/tgamauf/cypress-parallel/2.0.0/dist/index.js not supported.
Instead change the require of cypress.config.js in /home/runner/work/_actions/tgamauf/cypress-parallel/2.0.0/dist/index.js to a dynamic import() which is available in all CommonJS modules.
```

**I'm using:**

- Node `18.18.2`
- `2.0.0` of `cypress-parallel`
- `12.17.4` of Cypress
- `v6` of `cypress-io/github-action`

Thank you for your work on this action.

**Comment by tgamauf** [comment]
Hi, these are not supported, as noted at the top of the readme:

> This action currently does not support the defineConfig function in cypress.config.*js and cypress.config.ts config files and will fail if it is used.
